name: Tests
run-name: Running Tests
on: [push]
jobs:
  Run-PHPUnit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run PHPUnit Tests
        run: |
          vendor/bin/phpunit tests/
      - run: echo "Tests sucessfully executed!"
